version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: todo_app_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo_db
    ports:
      - "5432:5432"
    volumes:
      - ./tmp/postgres:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - app-network

  app:
    image: todo-app:latest
    build:
      context: ./todo-app
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/todo_db
    depends_on:
      - postgres
    networks:
      - app-network

  frontend:
    image: node:18
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: npx http-server -p 8081
    ports:
      - "8081:8081"
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge